server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/tingyu?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 10000
      validation-timeout: 3000

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

wechat:
  appid: ${WECHAT_APPID:}
  secret: ${WECHAT_SECRET:}
  subscribe:
    template-id: ${WECHAT_SUBSCRIBE_TEMPLATE_ID:pIleT1Y2QDm7fuGaHrRZ9X6GnP2ZCV0lbZoBVQJNiQo}
    page: ${WECHAT_SUBSCRIBE_PAGE:pages/detail/index}

tencent:
  tts:
    app-id: ${TENCENT_TTS_APP_ID:}
    secret-id: ${TENCENT_TTS_SECRET_ID:}
    secret-key: ${TENCENT_TTS_SECRET_KEY:}
    secret-token: ${TENCENT_TTS_SECRET_TOKEN:}
    region: ${TENCENT_TTS_REGION:ap-guangzhou}
    voice: ${TENCENT_TTS_VOICE:101001}
    speed: ${TENCENT_TTS_SPEED:0}
    volume: ${TENCENT_TTS_VOLUME:30}
