CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(64) NOT NULL COMMENT '用户ID',
    open_id VARCHAR(128) NOT NULL COMMENT '微信OpenID',
    nickname VARCHAR(100) NOT NULL COMMENT '微信昵称',
    avatar_url VARCHAR(500) DEFAULT NULL COMMENT '头像地址',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_open_id (open_id),
    KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信小程序用户表';
